### PR TITLE
Improved some util classes

### PR DESCRIPTION
**Pull request by SquareCodeFX**
The structure of important classes has been revised and improved. Tests were successful in my case. However, please conduct further tests.

### CODE REVIEW

**Comment by thomasmny** [comment]
Only had a quick look, but so far LGTM. However, could you revert the whitespace changes where all `=` are on the same height, e.g.:
Screenshot 2024-07-06 at 16 40 52

**Comment by SquareCodeFX** [comment]
You dont like it? XD

**Comment by thomasmny** [comment]
I prefer the normal style tbh

**Comment by SquareCodeFX** [comment]
Did i forget something?

**Pull request merged**
