### PR TITLE
Simple Axiom Support

### PR DESCRIPTION
**Pull request by EinJOJO**
Open for discussion

## What has changed
This update prevents users with axiom permissions (e.g. `axiom.*`) to modify worlds in which they normally do not have permission.

Therefore I refactored the listeners in order to reduce code duplication and have a central way of dealing with World-Manipulation.
I introduce the `WorldManipulationEvent` which can be fired with the `EventDispatcher`.
I tried to document those classes as precise as possible. It would be a duplicate to talk about them here. Please take a look at modified files.

⚠️ Nice to know when choosing settings. 
An axiom manipulation is considered as an `Interaction`, because it's not possible to differentiate axiom-manipulation between placing/breaking.

#### Library management

Sadly there is no maven-repo for AxiomPaper as far as I have seen, thus I used a jar placed in `libs/`.

**Question:** Should the jar be put there or stay referenced in ``libs/libs.txt``
The problem I have in mind is the CI-Server, which won't have the file during compile time when not included.

Easiest solution would be to include the jar file, but I don't know if it is wished.
Second solution would be to host the src on a repo (e.g https://repo.eintosti.de/#/).

I encourage everyone who feels like it to think of other test cases or think about some deeper integration of axiom

---

### Test Results
**Environment:**
Purpur 1.21.3
*Bukkit plugins (3):*
- AxiomPaper (4.0.2),
- Modified BuildSystem (2.25.3-SNAPSHOT),
- LuckPerms (5.4.149)
  Player A has `*` permissions
  Player B only has `axiom.*` permissions

When trying to test if axiom works, I make a selection of blocks and I try to *move* or *delete* them.
Further actions like *free draw* were not tested, because I expect that any axiom action triggers `AxiomModifyWorldEvent`

#### Test 1:  Builder Test (3/3)✅
1. A creates a public world, with Builders only setting.
B can not use Axiom ✅

2. B gets added to the world as builder
B can use Axiom and the world status changes from `Not started` to `In Progress` ✅

3. A archives the world
B can no longer modify the world. ✅

#### Test 2: partial setting test (3/3)✅
A turns `Builder only` off, Block Placement, Breaking and Interactions are on
B can normally interact with the world and axiom can be used.

In the following test, a single setting will be turned off, the other 2 are on

1. Interactions off:
> - Can no longer manually break/place blocks ✅
> - Axiom can not be used ✅ (considered as an interaction. see above)
(Attention when using `Tinker` (Change blockstate with rightclick)! Eventough the server cancels it, the client renders it differently) 
image

2. Block Placement off: 
> - B can not place blocks and can break ✅
> - Axiom can be used. ✅  (see above)

3. Block Breaking off .
> - Breaking manually not possible but place ✅
> - Using axiom is possible ✅ (see above)

### CODE REVIEW

**Comment by TWME-TW** [comment]
I'm not sure, but maybe you can get it from here

https://support.modrinth.com/en/articles/8801191-modrinth-maven

**Comment by thomasmny** [comment]
Very cool, thank you very much <3
Will have a look as soon as I can find some spare time

Regarding the repo: You can try using this
```kotlin
fun RepositoryHandler.modrinthMavenWorkaround(nameOrId: String, version: String, fileName: String) {
    val url = "https://api.modrinth.com/maven/maven/modrinth/$nameOrId/$version/$fileName"
    val group = "maven.modrinth.workaround"
    ivy(url.substringBeforeLast('/')) {
        name = "Modrinth Maven Workaround for $nameOrId"
        patternLayout { artifact(url.substringAfterLast('/')) }
        metadataSources { artifact() }
        content { includeModule(group, nameOrId) }
    }
}
```
and then in `repositiories`:
```
modrinthMavenWorkaround(
    "axiom-paper-plugin",
    "4.0.1-1.21.1",
    "AxiomPaper-4.0.1-for-MC1.21.1.jar"
)
```

**Comment by EinJOJO** [comment]
lgtm

**Review by thomasmny — APPROVED** [review]
Untested, but LGTM after having a quick skim over

**Comment by thomasmny** [comment]
Could you please move the listener initialisation to `registerExpansions()`?

**Comment by EinJOJO** [comment]
np

**Pull request merged**
